### ISSUE TITLE
Address sync and consistency issues under typical load scenarios

### ISSUE THREAD

**Issue by bmiller59** [berkmancenter/nymspace_client#45]
This is an epic ticket to cover the work outlined in the June 2024 SoW between Bocoup and BKC. This ticket may have sub issues as needed.

The goal is to resolve sync/consistency/performance issues under typical load scenarios. In particular, the most important scenario is the "hit the button" type of engagement in which many participants (e.g. 50 - 100) are simultaneously submitting responses at the same moment. 

* All users should see up to date, properly synced UI states in their browsers (Chrome, Firefox or Edge), without noticeable lag.
* There should be no dropped updates and the state of data in the database/server should also be correct.
* There should be automated tests to confirm these issues have been fixed in a reliable way.

**Comment by boazsender** [comment]
I mentioned this in the [commit message for the latest commit](https://github.com/bocoup/threads_client/commit/76f2e86691865255c88cd1c1f09421b182303adb) on PR #46, but wanted to call it out here so it doesn't get burried:

The bug that has been causing the app to feel broken appears to be a sync/consistency issue between logged-in and logged-out users, and not a performance issue. 

More specifically, messages from logged-in users were throwing a js error in the client for logged-out users because of conditional logic in the socket service which was not checking for this state when trying to send a message. Adding a check for this scenario fixes the bug from my initial testing. 

Here is a video that shows the the sync/consistency working between logged-in and logged-out users, as well as the prior buggy version: https://drive.proton.me/urls/9EM22E4JBG#8o8xorISk2r7

**Comment by boazsender** [comment]
On July 24th, a group of 11 people met to playtest the software. We ran through [this plan](https://docs.google.com/document/d/10nyqh9ri_A-Pv_kPQMZ9ZB2Aw2NTGe4VDoEzZeiMG-w/edit#heading=h.sn6vg5hop46h) where we also documented bugs. A summary of the bugs this team discovered, along with proposed fixes follows:

Category | Reported Behavior | Underlying Issue | Proposed Fix
-- | -- | -- | --
Security bug | Script and html can be injected | Html is unsanitized | Sanitize html, and add youtube embed support through URL
JS console error | on first page open, there are errors in firefox | w.value is undefined in firefox | investigate
JS console error | Clicking upvote fast multiple times | 500 response from the resulting XHR request | Investigate
JS console error | inability to downvote when logged out | Typeerror cannot read properties of null (reading ‘locked’) | remove downvote button when logged out and add a notice to that effect
JS console error | “unable to send message. Please try again later” | $.value is undefined | Try to reproduce this with load testing in the loop.
UI bug | Message count in new threads created by others do not display correctly until you post in the new thread or refresh the page | Message page only joins one thread at a time. | Join all threads on message page load.
UI bug | Unable to post in new thread that was created until I refresh | unkown | unkown
UX bug | New messages appear bellow the scroll of the message window and I don’t know that they are there. | New messages are hidden | Scroll automatically if I am scrolled downShow a snack bar indicating new messages if I am not scrolled down
UX bug | Voting buttons are hard to click | Voting buttons don’t always work | Increase space and click area around up/down vote buttons
UX bug | Cannot understand the full screen button | Full screen button is does not represent full screen well | Change full screen eyeball to a zoom/magnefying glass icon
UX bug | Favicon doesn’t match app | Boiler plate vuew favicon is still in use | Change the favicon to match the app
Mobile bug | Can’t read messages on mobile | The ui does not respond to screen size | Stack columns on mobile

Editing the issue to add checkboxes for each item.

**Comment by boazsender** [comment]
The following fixes are now in [bocoup/threads_client/tree/45-address-sync-and-consistency-issues-under-typical-load-scenarios](https://github.com/bocoup/threads_client/tree/45-address-sync-and-consistency-issues-under-typical-load-scenarios)

- ui change to stack columns on mobile
- app matching favicon added
- thread counts stay in sync

**Comment by boazsender** [comment]
I'm working on the task to increase space and click area around up/down vote buttons. I think the main problem here is that the the up/downvote buttons are the same UI as the up/downvote counters. This is too busy and tight to read/interact with. 

My solution is to separate them and put the up/downvote buttons into a hover menu. 

While doing this, I'm also adding an indicator of who "you" are in the UI to make it clearer when you cannot vote on your own messages.

I'm also adding a "time ago" indicator to the message since we have that information, and I think it helps with the experience of understanding what each row is. Happy to take this part out if it doesn't match the pseudonymous vision.

Here are some screenshots of what this looks like.

<img width="421" alt="image" src="https://github.com/user-attachments/assets/c6b8d8ca-3fe3-4724-b550-8fab54934576">
<img width="421" alt="image" src="https://github.com/user-attachments/assets/d6a4aca6-0a3c-4d58-8753-99077c9ff52e">
<img width="421" alt="image" src="https://github.com/user-attachments/assets/7d962ac8-6b0b-4115-8e9c-9c0782579acb">
<img width="421" alt="image" src="https://github.com/user-attachments/assets/251f3cb3-2cc4-4c57-9614-1032a6929d40">

**Comment by bmiller59** [comment]
Marking this ticket complete as all code has been QAed and merged into main branch.
